version: "3"
services:
    web:
        build: .
        restart: unless-stopped
        depends_on:
            - postgres
        links:
            - postgres
        networks:
            - backend
        env_file:
            - .env
        expose:
            - '80'
        ports:
            - '80:80'
    postgres:
        image: postgres:14.1
        restart: always
        ports:
            # <Port exposed> : < Port inside container>
            - '5433:5432'
        expose:
            # Opens port 5433 on the container
            - '5433'
        volumes:
            - database-data:/var/lib/postgresql/data/
        env_file: 
            - .env
        networks:
            - backend
    redis:
      image: redis:6.2.6
      restart: always
      ports:
        - "6379:6379"
      expose:
        - "6379"
networks:
    backend:
        driver: bridge

volumes:
  database-data: