version: "3"
services:
    web:
        build: .
        restart: unless-stopped
        depends_on:
            - cassandra
        links:
            - cassandra
        networks:
            - backend
        env_file:
            - .env
        expose:
            - '80'
        ports:
            - '80:80'
    cassandra:
        image: cassandra:4.0.1
        restart: always
        ports:
            # <Port exposed> : < Port inside container>
            - '7000:7000'
        expose:
            # Opens port 3306 on the container
            - '7000'
        volumes:
            - ./data/cassandra:/var/lib/cassandra
        env_file: 
            - .env
        networks:
            - backend
    redis:
      image: redis:6.2.6
      restart: always
      ports:
        - "6379:6379"
      expose:
        - "6379"
networks:
    backend:
        driver: bridge