version: "3"
services:
    web:
        build: .
        restart: unless-stopped
        depends_on:
            - postgres
            - redis
        links:
            - postgres
            - redis
        networks:
            - backend
        env_file:
            - .env
        expose:
            - '80'
        ports:
            - '80:80'
    postgres:
        image: mongo:5.0.5
        restart: always
        ports:
            # <Port exposed> : < Port inside container>
            - '27107:27107'
        expose:
            # Opens port 5433 on the container
            - '27107'
        volumes:
            - database-data:/var/lib/mongodb/data/
        env_file:
            - .env
        networks:
            - backend
    redis:
        image: redis:6.2.6
        restart: always
        ports:
            - "6379:6379"
        expose:
            - "6379"
        env_file:
            - .env
        networks:
            - backend
networks:
    backend:
        driver: bridge

volumes:
  database-data: